export interface User {
  id: string;
  username: string;
  avatar: string;
  badge?: string;
}

export interface Comment {
  id: string;
  user: User;
  content: string;
  timestamp: string;
  hypeScore?: number; // Generated by Gemini
  hypeReason?: string; // Generated by Gemini
  isWinner?: boolean;
}

export interface Thread {
  id: string;
  title: string;
  author: User;
  content: string;
  images: string[];
  views: number;
  likes: number;
  postedAt: string;
  deadline: Date;
}

export enum DrawStatus {
  UPCOMING = 'UPCOMING',
  OPEN = 'OPEN',
  CALCULATING = 'CALCULATING', // Rolling animation
  ENDED = 'ENDED'
}